facebook/between-meals

lib/between_meals/knife.rb
GD/TT assumes no versions. If there somehow got multiple versions, we
should not break.
=> Delete all cookbook versions

lib/between_meals/knife.rb
- berkshelf config is necessary when you want to upload to different chef servers as berkshelf will not honor the knife config specified in gd, instead it will look in default locations like ~/.chef/knife.rb. 
- bug fix for `berks_cookbook_upload_all` method, `cb` is already an absolute path and doesn't need the cookbook dir appended.
=> support for a berkshelf config and a bug fix

lib/between_meals/repo/hg.rb
Use 'hg export' instead of 'hg show' for better compatibility with standard mercurial installations. This closes #24
=> Use hg export instead of hg show

lib/between_meals/repo/git.rb
```
$ irb
irb(main):001:0> require 'rugged'
irb: symbol lookup error: /opt/chef/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/rugged-0.21.4/rugged/rugged.so: undefined symbol: SSL_load_error_strings
$ irb
irb(main):001:0> require 'openssl'
=> true
irb(main):002:0> require 'rugged'
=> true
irb(main):003:0>
```
I don't even.
=> Make rugged import safe(-ish)

lib/between_meals/repo.rb, lib/between_meals/repo/git.rb, lib/between_meals/repo/hg.rb, lib/between_meals/repo/svn.rb
This adds automated repo type detection, without breaking the convention of `.setup` always succeeding, and `.exists?` being the actual validation. So it happens that was already broken for git, since rugged was throwing an exception - that is fixed here.
Passes gd and tt full tests.
=> Auto detect repo type

lib/between_meals/repo/hg/cmd.rb
File cannot be empty, otherwise hg kicks off vi interactive session in the background, which just hangs.
=> Fix hg amend

.rubocop.yml, .travis.yml, lib/between_meals/changes/cookbook.rb, lib/between_meals/changeset.rb, lib/between_meals/cmd.rb, lib/between_meals/knife.rb, lib/between_meals/repo.rb, lib/between_meals/repo/git.rb, lib/between_meals/repo/hg.rb, lib/between_meals/repo/svn.rb, spec/cookbook_spec.rb, spec/databag_spec.rb, spec/git_spec.rb, spec/hg_spec.rb, spec/role_spec.rb, spec/svn_spec.rb
If we have malformed input (such as a space in a filename that can't be
handled), between-meals currently prints 'No match'. This error message
is not useful. Update the message and the specs.
=> update error message for failing to parse a repo status line

.travis.yml, Gemfile, circle.yml, lib/between_meals/repo/svn.rb
Rubgems < 2.6.9 prevents the rainbow gem from being installed.
See: sickill/rainbow#44
Partial fix for: facebook/between-meals#64
=> Fix ci build systems

lib/between_meals/cmd.rb
On macOS, one cannot install binaries to /bin or /usr/bin as they are locked down with SIP. hg is installed into /usr/local/bin, so without tweaking the PATH, this does not work on macOS.
I'm not sure if this is the best way to shim the path in, so suggestions are welcome ;)
=> Add /usr/local/bin to command path so macOS can find binaries correctly

.travis.yml, Gemfile, circle.yml
We no longer need to pin to these gems and should begin testing on 2.4
=> Removing old deps

circle.yml
We can define different ruby versions in containers that run in
parallel.
=> Begin using circle v2 and multiple containers

lib/between_meals/changes/cookbook.rb
Some cookbooks do not have a metadata.rb, such as berks vendor'ed cookbooks. Allow checking for deleted cookbooks based on metadata.rb -or- metadata.json file.
=> cookbook :deleted check for metadata.json

lib/between_meals/changes/change.rb, lib/between_meals/changes/cookbook.rb, lib/between_meals/changes/databag.rb, lib/between_meals/changes/role.rb, lib/between_meals/changeset.rb, lib/between_meals/knife.rb, lib/between_meals/util.rb
We're currently running into an issue where users are getting a 'No such file
or directory' error when knife tries to write a new pem in the default
dir. This is happening because the config dir != the pem dir, meaning only the config
dir is automatically created.
=> Create pem dir if it does not already exist

.rubocop.yml, between_meals.gemspec, lib/between_meals/repo/hg.rb
All modern ruby runtimes already include an implementation
=> Remove explicit dependency on 'json' rubygem

lib/between_meals/repo/hg/cmd.rb
The amend function is supposed to amend only the message not changes in the
repo. This seems to be the only way to do it in stock mercurial.
=> Fix message amend on hg

lib/between_meals/changes/cookbook.rb, spec/cookbook_spec.rb
If you end up deleting `metadata.json` while keeping `metadata.rb`, BM will
still treat this as deleting a cookbook. This PR provides and out: as long as
you are adding or modifying `metadata.rb`, you can delete `metadata.json`, or
vise-versa.
Signed-off-by: Phil Dibowitz <phil@ipom.com>
=> handle multiple MD files

lib/between_meals/util.rb
While testing chef_port_range for itchef, I noticed that port_open? was
incorrectly returning false. This was because we're currently only
checking whether 'localhost' is open, but not other IP addresses on a
host. Because taste-tester listens on '::', the check should be done for
each IP prior to returning a result.
=> Check all host IP addresses in port_open?

lib/between_meals/changes/cookbook.rb, lib/between_meals/changes/databag.rb, lib/between_meals/changes/role.rb, lib/between_meals/knife.rb, lib/between_meals/repo/git.rb, lib/between_meals/util.rb
In taste-tester's server code, we're only checking whether the state file's port param has a process listening on it (via port_open?). Adding a new helper (chef_zero_running?) to not only check that a process is listening on the port, but specifically a chef-zero proc.
Note - a corresponding change will also be needed in taste-tester to utilize this new helper within the server (https://github.com/facebook/taste-tester/pull/94).
=> Added new helper for testing whether chef-zero is running

.rubocop.yml, between_meals.gemspec
Pinning to rubocop version in chefdk 2.6 and syncing .rubocop.yml with to be consistent with the .rubocop.yml used for cookbooks.
=> Sync rubocop version and cops

Gemfile, between_meals.gemspec, lib/between_meals/changes/change.rb, lib/between_meals/changes/cookbook.rb, lib/between_meals/changes/databag.rb, lib/between_meals/changes/role.rb, lib/between_meals/changeset.rb, lib/between_meals/cmd.rb, lib/between_meals/knife.rb, lib/between_meals/repo.rb, lib/between_meals/repo/git.rb, lib/between_meals/repo/git/cmd.rb, lib/between_meals/repo/hg.rb, lib/between_meals/repo/hg/cmd.rb, lib/between_meals/repo/svn.rb, lib/between_meals/repo/svn/cmd.rb, lib/between_meals/util.rb, spec/cookbook_spec.rb, spec/databag_spec.rb, spec/git_spec.rb, spec/hg_spec.rb, spec/repo_spec.rb, spec/role_spec.rb, spec/spec_helper.rb, spec/svn_spec.rb
The inclusion of this comment without refactoring the code is resulting in a user's knife config failing to  being written out or updated. We can add these comments back to the code once it has been refactored to handle frozen strings correctly and the appropriate tests added to validate functionality.
trace:
```
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/between_meals-0.0.8/lib/between_meals/knife.rb:188:in `block in write_user_config': can't modify frozen String (RuntimeError)
from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/between_meals-0.0.8/lib/between_meals/knife.rb:187:in `each'
from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/between_meals-0.0.8/lib/between_meals/knife.rb:187:in `write_user_config'
from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/taste_tester-0.0.13/lib/t …
```
=> Remove frozen_string_literal magic comment

lib/between_meals/repo/hg.rb
If `hg pull` fails shell out throws exception, we catch it and try to log cmd.stdout. There are 2 issues with this:
1. cmd is not defined, but there is @cmd
2. The cmd object with stdout is returned as result as call, but since it's interruped with exception, we cannot get that stdout.
However, the exception itself includes everything, including stdout, so log the exception to have an info about the error logged.
=> Fix logging in hg repo update.

lib/between_meals/changes/cookbook.rb, spec/cookbook_spec.rb, spec/databag_spec.rb
Cookbooks that have been deleted and replaced with a symlinked cookbook in a changeset are currently marked as status 'deleted' instead of 'modified'. Taste-tester is knife deleting this cookbook, then failing dependent cookbook uploads, as the deleted cookbook is no longer being served by chef-zero. The only current way to resolve this is doing a forced upload.
To fix this - when processing symlinks, if we come across a metadata file that is marked as 'deleted', check in the symlink source directory if a metadata file exists. If so mark the metadata file as 'modified' and allow knife to re-upload rather than delete the cookbook.
=> Fix classification of cookbooks replaced with symlink

lib/between_meals/knife.rb
Fix for https://github.com/facebook/taste-tester/issues/122
taste-tester uses between-meals to run knife commands. If it's verbose (INFO or DEBUG), make knife verbose too to simplify debug.
=> Make knife verbose if logging level is DEBUG or INFO

lib/between_meals/repo/hg/cmd.rb
Summary: This will switch how 'hg' is doing pull.
Iriginally 'hg pull --rebase' used. The problem that it's not selfhealing. If for some reason working copy
has modified files - rebase often fails. Instead use two steps:
1) 'hg pull'
2) 'hg co master --clean'
This will allow to recover from localy modified files.
Test Plan:
/opt/chefdk/embedded/bin/ruby /opt/chefdk/embedded/bin/grocery-delivery -v -c /etc/gd-config.rb
WARN: Attempting to acquire lock
WARN: Lock acquired
WARN: Updating repo
INFO: Running "/usr/local/libexec/hg_wrapper_facebook pull"
INFO: Running "/usr/local/libexec/hg_wrapper_facebook checkout master --clean"
INFO: Running "/usr/local/libexec/hg_wrapper_facebook log -r . -l 1 -T '{node}'"
WARN: Repo has not changed, nothing to do...
WARN: Success at …
=> Pull changes from HG server in two steps

lib/between_meals/knife.rb
Creation of the working directory for taste-tester can fail when multiple instances try to make the directory; it's possible for the directory to not exist, such that the gate is passed, but then it exists before the mkdir call.
=> Don't fail taste-tester when working directory already exists

lib/between_meals/util.rb
taste-tester has a `run` mode that runs chef and streams the output in
real time. Rather than doing all this work manually, just enable users
of `BetweenMeals::Util` to use Mixlib::ShellOut's 'stream' options by
passing them through.
See https://github.com/facebook/taste-tester/pull/131 for a use-case.
Signed-off-by: Phil Dibowitz <phil@ipom.com>
=> Expose Mixlib::ShellOut's streaming in Utils

lib/between_meals/repo/git.rb, lib/between_meals/repo/hg.rb, lib/between_meals/repo/svn.rb, spec/git_spec.rb, spec/hg_spec.rb, spec/svn_spec.rb
If BM encounters a change that includes a file path with a space, it breaks. This changes the regex which maps a change in a given repository type to capture any character rather than only non whitespace. I can't find any other aspect of the parsing which depends on spaces, so I think this'll work.
=> Handle spaces in filenames

lib/between_meals/knife.rb
Some automation ends up running multiple copies of between_meals. I have
observed situations where the directory didn't exist, but by the time
mkdir was called, it did, so it crashed out. This uses similar logic to
FileUtils.mkdir_p to try to create the directory in any case, accept
failures as part of normal practice, and raise errors if the directory
*didn't* get created.
=> Eliminate mkdir race condition

lib/between_meals/cmd.rb, lib/between_meals/repo.rb, lib/between_meals/repo/git/cmd.rb, lib/between_meals/util.rb
Currently if `user.email` or `user.name` are not set, `git config`
returns an error. This means that if, if you're taste-tester plugin
you check to see if it's config, taste-tester just blows up deep
inside the bowels of between-meals, which is suboptimal.
Since `git config` returns 1 in the case of no config set, let's
accept that as a valid response.
=> Better handling for git config

lib/between_meals/repo/git.rb
I know that FB's git was git-over-svn, but that's not the common-case,
so default to a more common git case.
Since nearly everyone is already overriding this who uses it, and FB
no longer uses git, this should be safe.
=> Do not assume git-svn in the git plugin

lib/between_meals/repo.rb, lib/between_meals/repo/git.rb
For the repo checks hook it's useful to get access to the rugged object
to do sanity checks without having to shell out. This provides an
accessor.
It's done specifically in the git module because it's the only module
in which we use such a library, the other ones are simple shellouts.
=> Allow users to get access to the Rugged object

.github/workflows/ci.yml, CONTRIBUTING.md
The default branch is now named "main", updating workflows and documentation to reflect the change
=> Update default branch name

.github/workflows/ci.yml
Trivial fix for https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> [github] Use actions/checkout@v3

spec/git_spec.rb, spec/hg_spec.rb, spec/repo_subclass_conformance.rb, spec/svn_spec.rb
The aim of this refactor is to make the BetweenMeals internals testing more repo-agnostic, isolating RCS-specific issues (ie rugged/git) to specific class tests.
=> De-couple BetweenMeals::Repo class conformance tests

lib/between_meals/changes/change.rb, lib/between_meals/changes/cookbook.rb, lib/between_meals/changes/databag.rb, lib/between_meals/changes/role.rb, spec/cookbook_spec.rb, spec/databag_spec.rb, spec/role_spec.rb
Summary:
For changes detection we don't care if file was added or modified or have any other status provided by VCS, we only need to understand if file was modified or deleted. So using same logic as in BetweenMeals::Changes::Role
This would fix an issue with Grocery Delivery uploads when adding new databag.
=> Fix change detection for databags

lib/between_meals/repo.rb
Addresses #130 
This changes the default behavior of auto-detection from git to hg, so that rugged isn't loaded unless it's testing for a git repository.
=> Have repo auto-detection lazily load repository libraries

Gemfile, between_meals.gemspec
With 396dd8f4d3c7dcae9825951cad906ee2b98ca78b committed, we can put `rugged` into a gemfile group, which allows `bundle install --without git`
=> Move rugged dependency into git gem group

lib/between_meals/knife.rb
We're expecting the output of `knife data bag list` to be JSON, but with `-VV` this can have non-JSON output which looks like:
```
Uploading databags...
Upload failed
unexpected token at 'INFO: Using configuration from /fake/.chef/knife-dcrosby-taste-tester.rb
[
"foo"
]
'
```
=> Remove verbosity options from data bag list shellout

.github/workflows/ci.yml, Gemfile, between_meals.gemspec, spec/git_spec.rb
While we still want to keep testing `rugged` on the Github CI, it's not necessary everywhere (and building rugged is a PITA).
=> [rspec] Only test rugged extension if rugged gem is available

lib/between_meals/knife.rb
Got a repro of #144. Let's remove the first line of the stdout if it's a logging message.
=> [#create_databag_if_missing] Remove preceding log message before parsing JSON
